'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------



Public Partial Class [Default]

	''' <summary>
	''' Head1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

	''' <summary>
	''' Form1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

	''' <summary>
	''' QueryBuilderUC1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected QueryBuilderUC1 As Global.ToggleUseAltNames.QueryBuilderToggleUseAltNames
End Class
