'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class InteractWitnAspNetControls

	'''<summary>
	'''form1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

	'''<summary>
	'''ScriptManager1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

	'''<summary>
	'''QueryBuilderControl1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents QueryBuilderControl1 As Global.ActiveDatabaseSoftware.ActiveQueryBuilder.Web.Control.QueryBuilderControl

	'''<summary>
	'''UpdatePanel1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

	'''<summary>
	'''label control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents label As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''button control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents button As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''ObjectTree1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ObjectTree1 As Global.ActiveDatabaseSoftware.ActiveQueryBuilder.Web.Control.ObjectTreeView 

	'''<summary>
	'''Canvas1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Canvas1 As Global.ActiveDatabaseSoftware.ActiveQueryBuilder.Web.Control.Canvas

	'''<summary>
	'''Grid1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Grid1 As Global.ActiveDatabaseSoftware.ActiveQueryBuilder.Web.Control.Grid

	'''<summary>
	'''StatusBar1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents StatusBar1 As Global.ActiveDatabaseSoftware.ActiveQueryBuilder.Web.Control.StatusBar

	'''<summary>
	'''SQLEditor1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents SQLEditor1 As Global.ActiveDatabaseSoftware.ActiveQueryBuilder.Web.Control.SqlEditor
End Class
