'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------



Public Partial Class QueryBuilderOffline

	''' <summary>
	''' QueryBuilderControl1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected QueryBuilderControl1 As Global.ActiveDatabaseSoftware.ActiveQueryBuilder.Web.Control.QueryBuilderControl

	''' <summary>
	''' ObjectTree1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ObjectTree1 As Global.ActiveDatabaseSoftware.ActiveQueryBuilder.Web.Control.ObjectTreeView

	''' <summary>
	''' SubQueryNavigationBar1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected SubQueryNavigationBar1 As Global.ActiveDatabaseSoftware.ActiveQueryBuilder.Web.Control.SubQueryNavigationBar

	''' <summary>
	''' Canvas1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected Canvas1 As Global.ActiveDatabaseSoftware.ActiveQueryBuilder.Web.Control.Canvas

	''' <summary>
	''' StatusBar1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected StatusBar1 As Global.ActiveDatabaseSoftware.ActiveQueryBuilder.Web.Control.StatusBar

	''' <summary>
	''' Grid1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected Grid1 As Global.ActiveDatabaseSoftware.ActiveQueryBuilder.Web.Control.Grid

	''' <summary>
	''' SQLEditor1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected SQLEditor1 As Global.ActiveDatabaseSoftware.ActiveQueryBuilder.Web.Control.SqlEditor
End Class
