'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class QueryBuilderOffline

	'''<summary>
	'''QueryBuilderControl1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents QueryBuilderControl1 As Global.ActiveDatabaseSoftware.ActiveQueryBuilder.Web.Control.QueryBuilderControl

	'''<summary>
	'''textBox1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents textBox1 As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''buttonAnalyzeQuery control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents buttonAnalyzeQuery As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''buttonQueryStatistics control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents buttonQueryStatistics As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''buttonAnalyzeMetadataContainer control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents buttonAnalyzeMetadataContainer As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''buttonAnalyzeWhereClause control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents buttonAnalyzeWhereClause As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''tbResult control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tbResult As Global.System.Web.UI.WebControls.TextBox
End Class
