'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class QueryBuilderOffline

	'''<summary>
	'''tbSQL control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tbSQL As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''cbCustomers control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cbCustomers As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''cbCompanyName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cbCompanyName As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''tbCompanyName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tbCompanyName As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''cbOrders control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cbOrders As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''cbOrderDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cbOrderDate As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''tbOrderDate control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents tbOrderDate As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnQueryCustomers control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnQueryCustomers As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnQueryOrders control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnQueryOrders As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnQueryCustomersOrders control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnQueryCustomersOrders As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''btnApply control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnApply As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''QueryBuilderControl1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents QueryBuilderControl1 As Global.ActiveDatabaseSoftware.ActiveQueryBuilder.Web.Control.QueryBuilderControl

	'''<summary>
	'''ObjectTree1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ObjectTree1 As Global.ActiveDatabaseSoftware.ActiveQueryBuilder.Web.Control.ObjectTreeView 

	'''<summary>
	'''SubQueryNavigationBar1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents SubQueryNavigationBar1 As Global.ActiveDatabaseSoftware.ActiveQueryBuilder.Web.Control.SubQueryNavigationBar

	'''<summary>
	'''Canvas1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Canvas1 As Global.ActiveDatabaseSoftware.ActiveQueryBuilder.Web.Control.Canvas

	'''<summary>
	'''Grid1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Grid1 As Global.ActiveDatabaseSoftware.ActiveQueryBuilder.Web.Control.Grid

	'''<summary>
	'''StatusBar1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents StatusBar1 As Global.ActiveDatabaseSoftware.ActiveQueryBuilder.Web.Control.StatusBar

	'''<summary>
	'''SQLEditor1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents SQLEditor1 As Global.ActiveDatabaseSoftware.ActiveQueryBuilder.Web.Control.SqlEditor
End Class
