'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class QueryBuilderOffline
    
    '''<summary>
    '''QueryBuilderControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QueryBuilderControl1 As Global.ActiveDatabaseSoftware.ActiveQueryBuilder.Web.Control.QueryBuilderControl
    
    '''<summary>
    '''btn1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn1 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn2 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn3 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn4 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ObjectTree1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ObjectTree1 As Global.ActiveDatabaseSoftware.ActiveQueryBuilder.Web.Control.ObjectTreeView 
    
    '''<summary>
    '''SubQueryNavigationBar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubQueryNavigationBar1 As Global.ActiveDatabaseSoftware.ActiveQueryBuilder.Web.Control.SubQueryNavigationBar
    
    '''<summary>
    '''Canvas1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Canvas1 As Global.ActiveDatabaseSoftware.ActiveQueryBuilder.Web.Control.Canvas
    
    '''<summary>
    '''StatusBar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusBar1 As Global.ActiveDatabaseSoftware.ActiveQueryBuilder.Web.Control.StatusBar
    
    '''<summary>
    '''Grid1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grid1 As Global.ActiveDatabaseSoftware.ActiveQueryBuilder.Web.Control.Grid
    
    '''<summary>
    '''SQLEditor1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SQLEditor1 As Global.ActiveDatabaseSoftware.ActiveQueryBuilder.Web.Control.SqlEditor
End Class
